### PR TITLE
Cards and images

### PR DESCRIPTION
**Pull request by tanveertkd**

### CODE REVIEW

**Review by msdeshmukh009 — APPROVED** [review]
The cards really look nice, Only one thing, the badge on the cards are going a little out of the container maybe you can fix that if it's not intentional.

**Comment by Chakravarthi0** [comment]
Looks great!

**Review by Chakravarthi0 — APPROVED** [review]
Looks great!

**Review by mimansha-swarup — APPROVED** [review]
looks Good to me 
UI is clean 🔥

**Comment by tanveertkd** [comment]
@msdeshmukh009 Oh that actually is intentional.

**Pull request merged**
