### PR TITLE
Avatars and alerts

### PR DESCRIPTION
**Pull request by tanveertkd**
Added avatars and alerts

### CODE REVIEW

**Review by manojasarsa — APPROVED** [review]
Looks clean! Just a small suggestion, if the background color of avatars is more brighter so that varieties of avatars can be clearly visible.

**Review by horsemaker — COMMENTED** [review]
for the yellow in alerts, the contrast seems low, both ways (readability issues)
also, are the alerts supposed to take the full width? 🤔

otherwise, looks clean! 👍

**Comment by tanveertkd** [comment]
@horsemaker I totally spaced out about the alert width. Thanks! I have made the changes.

**Comment by tanveertkd** [comment]
@manojasarsa @horsemaker The contrast does seem a bit low. I'll keep it in mind.

**Review by vijaytembugade — APPROVED** [review]
If it is not rough draft, and you are working on documentation + component , you can look at some responsiveness, bacause, in mobile view horizontal axis shows.

**Review by poornima-alugubelly — APPROVED** [review]
Hey Tanveer looks good! Just a suggestion if you want to remove the vertical scroll from the iframe just add scrolling="no" in the inline styles of it

**Review by MarkVed17 — APPROVED** [review]
These components look really good, Tanveer. Are you yet to make the list of components drawer to the left? As I can see the list of components is at the top on every page of your components.

**Comment by tanveertkd** [comment]
@poornima-alugubelly Thanks for pointing it out! I'll check that.

**Comment by tanveertkd** [comment]
@MarkVed17 That was not intentional, I messed up the layout. Fixed it now. Thank you!

**Pull request merged**
